pages:
- Home: 'index.md'
- Quickstart: 'quickstart.md'
- Recipes: 'recipes.md'
- References:
    - Layouts: 'layouts.md'
    - Components: 'components.md'
    - Events: 'events.md'
    - Themes: 'themes.md'
- Versions: 'versions.md'
- About: 'about.md'

site_name: vermui
repo_url: https://github.com/verdverm/vermui/
site_description: 'vermui user guide'
site_author: verdverm

docs_dir: '_docs'

theme: readthedocs

markdown_extensions:
  - smarty
  - admonition
  - toc

extra:
    version: 1.0
